<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/SPRDNK.glb
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, FakeGlowMaterial } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/SPRDNK.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
  <T.Group position={[-4, 0, 0]} rotation={[0.63, -0.82, 0.94]} scale={0.01}>
    <T.Group>
      <T.Mesh geometry={gltf.nodes.Mesh_1.geometry} material={gltf.materials['Material.002']}/>
      <T.Mesh geometry={gltf.nodes.Mesh_1_1.geometry} material={gltf.materials['Material.003']}>
        <FakeGlowMaterial glowColor="red" falloff={0.1} glowInternalRadius={-1}/>
      </T.Mesh>
      <T.Mesh geometry={gltf.nodes.Mesh_1_2.geometry} material={gltf.materials['Material.004']} />
    </T.Group>
  </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
