// Code generated by Slice Machine. DO NOT EDIT.

import BlogPost from './BlogPost/index.svelte';
import GamesList from './GamesList/index.svelte';
import Hero from './Hero/index.svelte';
import NewsSlot from './NewsSlot/index.svelte';

export const components = {
	blog_post: BlogPost,
	games_list: GamesList,
	hero: Hero,
	news_slot: NewsSlot
};
