// Code generated by Slice Machine. DO NOT EDIT.

import BlogPost from './BlogPost/index.svelte';
import GamesList from './GamesList/index.svelte';
import Hero from './Hero/index.svelte';
import MerchTShirt from './MerchTShirt/index.svelte';
import NewsSlot from './NewsSlot/index.svelte';
import RosterList from './RosterList/index.svelte';

export const components = {
	blog_post: BlogPost,
	games_list: GamesList,
	hero: Hero,
	merch_t_shirt: MerchTShirt,
	news_slot: NewsSlot,
	roster_list: RosterList
};
