// Code generated by Slice Machine. DO NOT EDIT.

import GamesList from './GamesList/index.svelte';
import Hero from './Hero/index.svelte';
import NewsSlot from './NewsSlot/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	games_list: GamesList,
	hero: Hero,
	news_slot: NewsSlot,
	rich_text: RichText
};
